### ISSUE TITLE
Custom cache version cannot be a number

### ISSUE THREAD

**Issue by imakewebthings** [poeticninja/hapi-cache-buster#3]
Because lodash's `isEmpty` returns true for numbers (as they don't have a length property) if you pass a number as the `options` it will use the package version instead. Right now options must be a string. That's fine, except the documentation uses the word number. This should either:

- Change docs to clarify a string, or...
- Allow numbers.

Thanks for the plugin, Saul.

**Comment by poeticninja** [comment]
Good catch. I think allowing for a number or string would be good. I will update as soon as I get a chance. I am glad the plugin is helpful!

**Comment by poeticninja** [comment]
This was fixed and I also added tests. 6c5c8ddbcbf3f79cdb082012eb36c382b640b917
